[phases.setup]
aptPkgs = [
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libxss1",
  "libasound2",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libpangocairo-1.0-0",
  "libgtk-3-0",
  "ca-certificates"
]
