[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

installCommand = "cd Backend/server && npm install"

[start]
startCommand = "cd Backend/server && npm start"

[deploy]
restartPolicyType = "ON_FAILURE"
